### ISSUE TITLE
窗口转化后大小不一致

### ISSUE THREAD

**Issue by ShiJunY** [jerryxjr1220/aardioGUI2Python#2]
aardio中的窗口为right=757，bottom=467
`
import win.ui;
/*DSG{{*/
mainForm = win.form(text="Hello";right=757;bottom=467;max=false)
mainForm.add(
button_Click={cls="button";text="点我";left=592;top=16;right=738;bottom=60;z=2};
edit_Click={cls="edit";left=19;top=13;right=575;bottom=452;edge=1;multiline=1;z=1}
)
/*}}*/

import GUI2Py
g2p = GUI2Py.GUI2Tk( mainForm );
g2p.transfer2place( "Hello" ); //这里的Hello就是py文件中的类名

//把上面的DSG代码复制到这里
g2p.translateName(`
button_Click={cls="button";text="点我";left=592;top=16;right=738;bottom=60;z=2};
edit_Click={cls="edit";left=19;top=13;right=575;bottom=452;edge=1;multiline=1;z=1}
`)

string.save("/res/demo.py", g2p.pycode)

mainForm.show();
return win.loopMessage();
`

转化为py文件后，位置发生变化，编辑框控件原来四周贴边，现在下方空出一大段
`
import tkinter as tk
import tkinter.ttk as ttk
import tkinter.font as tkFont

class Hello():
    ### 界面设计部分 ###
    
    def __init__(self, master):
        self.mainframe = ttk.Frame(master, width=774, height=507)
        self.editVar1 = tk.StringVar(value="")
        self.edit_Click_frame = ttk.Frame(width=556, height=439)
        self.edit_Click = tk.Text(self.edit_Click_frame)
        self.edit_Click.insert("end", "")
        self.edit_Click.place(x=0, y=0, width=556, height=439)
        self.edit_Click_font = tkFont.Font(family="Segoe UI", size=9, weight="normal", slant="roman", underline=False)
        self.edit_Click.configure(font=self.edit_Click_font)
        self.edit_Click_frame.place(x=19, y=13)
        self.button_Click_frame = ttk.Frame(width=146, height=44)
        self.button_Click = ttk.Button(self.button_Click_frame, text="点我")
        self.button_Click.place(x=0, y=0, width=146, height=44)
        self.button_Click_frame.place(x=592, y=16)
        self.mainframe.pack()

    ### 功能逻辑部分 ###

root = tk.Tk()
Hello(root)
root.mainloop()

`

**Comment by jerryxjr1220** [comment]
你可以查看一下GUI2Py.aardio的源码，其中关于窗口大小的定义是这样的
`owner.write(..string.format('root.geometry("%ix%i")', window_width, window_height));`
也就是说直接引用的aardio中窗口的宽度和高度，理论上来说应该是与原窗口保持一致的。

如果你发现窗口大小不一致，可以排查一下是否窗口或者屏幕开启了放缩？
如果还是不能解决你的问题的话，你可以自行调整`window_width`或者`window_height`使之与你的屏幕匹配。
